# TCL File Generated by Component Editor 8.0
# Thu Nov 19 16:40:12 EST 2009
# DO NOT MODIFY


# +-----------------------------------
# | 
# | gpu_dma_interface "gpu_dma_interface" v1.0
# | null 2009.11.19.16:40:12
# | 
# | 
# | C:/576/gpu/controller/gpu_dma_interface.v
# | 
# |    ./gpu_dma_interface.v syn, sim
# | 
# +-----------------------------------


# +-----------------------------------
# | module gpu_dma_interface
# | 
set_module_property NAME gpu_dma_interface
set_module_property VERSION 1.0
set_module_property GROUP ""
set_module_property DISPLAY_NAME gpu_dma_interface
set_module_property TOP_LEVEL_HDL_FILE gpu_dma_interface.v
set_module_property TOP_LEVEL_HDL_MODULE gpu_dma_interface
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property SIMULATION_MODEL_IN_VERILOG false
set_module_property SIMULATION_MODEL_IN_VHDL false
set_module_property SIMULATION_MODEL_HAS_TULIPS false
set_module_property SIMULATION_MODEL_IS_OBFUSCATED false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file gpu_dma_interface.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end
set_interface_property clock_reset ptfSchematicName ""

add_interface_port clock_reset clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point gpu_read__dma__write_interface
# | 
add_interface gpu_read__dma__write_interface avalon end
set_interface_property gpu_read__dma__write_interface holdTime 0
set_interface_property gpu_read__dma__write_interface linewrapBursts false
set_interface_property gpu_read__dma__write_interface minimumUninterruptedRunLength 1
set_interface_property gpu_read__dma__write_interface bridgesToMaster ""
set_interface_property gpu_read__dma__write_interface isMemoryDevice false
set_interface_property gpu_read__dma__write_interface burstOnBurstBoundariesOnly false
set_interface_property gpu_read__dma__write_interface addressSpan 2
set_interface_property gpu_read__dma__write_interface timingUnits Cycles
set_interface_property gpu_read__dma__write_interface setupTime 0
set_interface_property gpu_read__dma__write_interface writeWaitTime 0
set_interface_property gpu_read__dma__write_interface isNonVolatileStorage false
set_interface_property gpu_read__dma__write_interface addressAlignment DYNAMIC
set_interface_property gpu_read__dma__write_interface maximumPendingReadTransactions 0
set_interface_property gpu_read__dma__write_interface readWaitTime 1
set_interface_property gpu_read__dma__write_interface readLatency 0
set_interface_property gpu_read__dma__write_interface printableDevice false

set_interface_property gpu_read__dma__write_interface ASSOCIATED_CLOCK clock_reset

add_interface_port gpu_read__dma__write_interface int__dma__ready readyfordata Output 1
add_interface_port gpu_read__dma__write_interface dma__int__write write Input 1
add_interface_port gpu_read__dma__write_interface dma__int__data_out writedata Input 16
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ASSOCIATED_CLOCK clock_reset

add_interface_port conduit_end int__gpu__write export Output 1
add_interface_port conduit_end gpu__int__ready export Input 1
add_interface_port conduit_end int__gpu__data_out export Output 16
add_interface_port conduit_end int__gpu__clk export Output 1
# | 
# +-----------------------------------
