/****************************************************************
 * Skyler Schneider ss868                                       *
 * ECE 5760 Final Project                                       *
 * Sand Game                                                    *
 ****************************************************************/

`define SC_NONE                     8'h00

`define SC_MAKE_PAUSE               8'h80
`define SC_MAKE_ESC                 8'h81
`define SC_MAKE_F1                  8'h82
`define SC_MAKE_F2                  8'h83
`define SC_MAKE_F3                  8'h84
`define SC_MAKE_F4                  8'h85
`define SC_MAKE_F5                  8'h86
`define SC_MAKE_F6                  8'h87
`define SC_MAKE_F7                  8'h88
`define SC_MAKE_F8                  8'h89
`define SC_MAKE_F9                  8'h8A
`define SC_MAKE_F10                 8'h8B
`define SC_MAKE_F11                 8'h8C
`define SC_MAKE_F12                 8'h8D
`define SC_MAKE_PRT_SCR             8'h8E
`define SC_MAKE_SCR_LOCK            8'h8F
`define SC_MAKE_TILDE               8'h90
`define SC_MAKE_1                   8'h91
`define SC_MAKE_2                   8'h92
`define SC_MAKE_3                   8'h93
`define SC_MAKE_4                   8'h94
`define SC_MAKE_5                   8'h95
`define SC_MAKE_6                   8'h96
`define SC_MAKE_7                   8'h97
`define SC_MAKE_8                   8'h98
`define SC_MAKE_9                   8'h99
`define SC_MAKE_0                   8'h9A
`define SC_MAKE_MINUS               8'h9B
`define SC_MAKE_EQUALS              8'h9C
`define SC_MAKE_BACKSPACE           8'h9D
`define SC_MAKE_TAB                 8'h9E
`define SC_MAKE_Q                   8'h9F
`define SC_MAKE_W                   8'hA0
`define SC_MAKE_E                   8'hA1
`define SC_MAKE_R                   8'hA2
`define SC_MAKE_T                   8'hA3
`define SC_MAKE_Y                   8'hA4
`define SC_MAKE_U                   8'hA5
`define SC_MAKE_I                   8'hA6
`define SC_MAKE_O                   8'hA7
`define SC_MAKE_P                   8'hA8
`define SC_MAKE_LF_BRACKET          8'hA9
`define SC_MAKE_RT_BRACKET          8'hAA
`define SC_MAKE_BACKSLASH           8'hAB
`define SC_MAKE_CAPS_LOCK           8'hAC
`define SC_MAKE_A                   8'hAD
`define SC_MAKE_S                   8'hAE
`define SC_MAKE_D                   8'hAF
`define SC_MAKE_F                   8'hB0
`define SC_MAKE_G                   8'hB1
`define SC_MAKE_H                   8'hB2
`define SC_MAKE_J                   8'hB3
`define SC_MAKE_K                   8'hB4
`define SC_MAKE_L                   8'hB5
`define SC_MAKE_SEMICOLON           8'hB6
`define SC_MAKE_APOSTROPHE          8'hB7
`define SC_MAKE_ENTER               8'hB8
`define SC_MAKE_LF_SHIFT            8'hB9
`define SC_MAKE_Z                   8'hBA
`define SC_MAKE_X                   8'hBB
`define SC_MAKE_C                   8'hBC
`define SC_MAKE_V                   8'hBD
`define SC_MAKE_B                   8'hBE
`define SC_MAKE_N                   8'hBF
`define SC_MAKE_M                   8'hC0
`define SC_MAKE_COMMA               8'hC1
`define SC_MAKE_PERIOD              8'hC2
`define SC_MAKE_FRONTSLASH          8'hC3
`define SC_MAKE_RT_SHIFT            8'hC4
`define SC_MAKE_LF_CTRL             8'hC5
`define SC_MAKE_LF_WINDOWS          8'hC6
`define SC_MAKE_LF_ALT              8'hC7
`define SC_MAKE_SPACE               8'hC8
`define SC_MAKE_RT_ALT              8'hC9
`define SC_MAKE_RT_WINDOWS          8'hCA
`define SC_MAKE_MENUS               8'hCB
`define SC_MAKE_RT_CTRL             8'hCC
`define SC_MAKE_INSERT              8'hCD
`define SC_MAKE_HOME                8'hCE
`define SC_MAKE_PAGE_UP             8'hCF
`define SC_MAKE_DEL                 8'hD0
`define SC_MAKE_END                 8'hD1
`define SC_MAKE_PAGE_DOWN           8'hD2
`define SC_MAKE_UP_ARROW            8'hD3
`define SC_MAKE_LEFT_ARROW          8'hD4
`define SC_MAKE_DOWN_ARROW          8'hD5
`define SC_MAKE_RIGHT_ARROW         8'hD6
`define SC_MAKE_NUM_LOCK            8'hD7
`define SC_MAKE_NUMPAD_FRONTSLASH   8'hD8
`define SC_MAKE_NUMPAD_ASTERISK     8'hD9
`define SC_MAKE_NUMPAD_MINUS        8'hDA
`define SC_MAKE_NUMPAD_7            8'hDB
`define SC_MAKE_NUMPAD_8            8'hDC
`define SC_MAKE_NUMPAD_9            8'hDD
`define SC_MAKE_NUMPAD_PLUS         8'hDE
`define SC_MAKE_NUMPAD_4            8'hDF
`define SC_MAKE_NUMPAD_5            8'hE0
`define SC_MAKE_NUMPAD_6            8'hE1
`define SC_MAKE_NUMPAD_1            8'hE2
`define SC_MAKE_NUMPAD_2            8'hE3
`define SC_MAKE_NUMPAD_3            8'hE4
`define SC_MAKE_NUMPAD_0            8'hE5
`define SC_MAKE_NUMPAD_PERIOD       8'hE6
`define SC_MAKE_NUMPAD_ENTER        8'hE7

`define SC_BREAK_ESC                8'h01
`define SC_BREAK_F1                 8'h02
`define SC_BREAK_F2                 8'h03
`define SC_BREAK_F3                 8'h04
`define SC_BREAK_F4                 8'h05
`define SC_BREAK_F5                 8'h06
`define SC_BREAK_F6                 8'h07
`define SC_BREAK_F7                 8'h08
`define SC_BREAK_F8                 8'h09
`define SC_BREAK_F9                 8'h0A
`define SC_BREAK_F10                8'h0B
`define SC_BREAK_F11                8'h0C
`define SC_BREAK_F12                8'h0D
`define SC_BREAK_PRT_SCR            8'h0E
`define SC_BREAK_SCR_LOCK           8'h0F
`define SC_BREAK_TILDE              8'h10
`define SC_BREAK_1                  8'h11
`define SC_BREAK_2                  8'h12
`define SC_BREAK_3                  8'h13
`define SC_BREAK_4                  8'h14
`define SC_BREAK_5                  8'h15
`define SC_BREAK_6                  8'h16
`define SC_BREAK_7                  8'h17
`define SC_BREAK_8                  8'h18
`define SC_BREAK_9                  8'h19
`define SC_BREAK_0                  8'h1A
`define SC_BREAK_MINUS              8'h1B
`define SC_BREAK_EQUALS             8'h1C
`define SC_BREAK_BACKSPACE          8'h1D
`define SC_BREAK_TAB                8'h1E
`define SC_BREAK_Q                  8'h1F
`define SC_BREAK_W                  8'h20
`define SC_BREAK_E                  8'h21
`define SC_BREAK_R                  8'h22
`define SC_BREAK_T                  8'h23
`define SC_BREAK_Y                  8'h24
`define SC_BREAK_U                  8'h25
`define SC_BREAK_I                  8'h26
`define SC_BREAK_O                  8'h27
`define SC_BREAK_P                  8'h28
`define SC_BREAK_LF_BRACKET         8'h29
`define SC_BREAK_RT_BRACKET         8'h2A
`define SC_BREAK_BACKSLASH          8'h2B
`define SC_BREAK_CAPS_LOCK          8'h2C
`define SC_BREAK_A                  8'h2D
`define SC_BREAK_S                  8'h2E
`define SC_BREAK_D                  8'h2F
`define SC_BREAK_F                  8'h30
`define SC_BREAK_G                  8'h31
`define SC_BREAK_H                  8'h32
`define SC_BREAK_J                  8'h33
`define SC_BREAK_K                  8'h34
`define SC_BREAK_L                  8'h35
`define SC_BREAK_SEMICOLON          8'h36
`define SC_BREAK_APOSTROPHE         8'h37
`define SC_BREAK_ENTER              8'h38
`define SC_BREAK_LF_SHIFT           8'h39
`define SC_BREAK_Z                  8'h3A
`define SC_BREAK_X                  8'h3B
`define SC_BREAK_C                  8'h3C
`define SC_BREAK_V                  8'h3D
`define SC_BREAK_B                  8'h3E
`define SC_BREAK_N                  8'h3F
`define SC_BREAK_M                  8'h40
`define SC_BREAK_COMMA              8'h41
`define SC_BREAK_PERIOD             8'h42
`define SC_BREAK_FRONTSLASH         8'h43
`define SC_BREAK_RT_SHIFT           8'h44
`define SC_BREAK_LF_CTRL            8'h45
`define SC_BREAK_LF_WINDOWS         8'h46
`define SC_BREAK_LF_ALT             8'h47
`define SC_BREAK_SPACE              8'h48
`define SC_BREAK_RT_ALT             8'h49
`define SC_BREAK_RT_WINDOWS         8'h4A
`define SC_BREAK_MENUS              8'h4B
`define SC_BREAK_RT_CTRL            8'h4C
`define SC_BREAK_INSERT             8'h4D
`define SC_BREAK_HOME               8'h4E
`define SC_BREAK_PAGE_UP            8'h4F
`define SC_BREAK_DEL                8'h50
`define SC_BREAK_END                8'h51
`define SC_BREAK_PAGE_DOWN          8'h52
`define SC_BREAK_UP_ARROW           8'h53
`define SC_BREAK_LEFT_ARROW         8'h54
`define SC_BREAK_DOWN_ARROW         8'h55
`define SC_BREAK_RIGHT_ARROW        8'h56
`define SC_BREAK_NUM_LOCK           8'h57
`define SC_BREAK_NUMPAD_FRONTSLASH  8'h58
`define SC_BREAK_NUMPAD_ASTERISK    8'h59
`define SC_BREAK_NUMPAD_MINUS       8'h5A
`define SC_BREAK_NUMPAD_7           8'h5B
`define SC_BREAK_NUMPAD_8           8'h5C
`define SC_BREAK_NUMPAD_9           8'h5D
`define SC_BREAK_NUMPAD_PLUS        8'h5E
`define SC_BREAK_NUMPAD_4           8'h5F
`define SC_BREAK_NUMPAD_5           8'h60
`define SC_BREAK_NUMPAD_6           8'h61
`define SC_BREAK_NUMPAD_1           8'h62
`define SC_BREAK_NUMPAD_2           8'h63
`define SC_BREAK_NUMPAD_3           8'h64
`define SC_BREAK_NUMPAD_0           8'h65
`define SC_BREAK_NUMPAD_PERIOD      8'h66
`define SC_BREAK_NUMPAD_ENTER       8'h67
