	Computer_System u0 (
		.adc_sclk                   (<connected-to-adc_sclk>),                   //                  adc.sclk
		.adc_cs_n                   (<connected-to-adc_cs_n>),                   //                     .cs_n
		.adc_dout                   (<connected-to-adc_dout>),                   //                     .dout
		.adc_din                    (<connected-to-adc_din>),                    //                     .din
		.audio_ADCDAT               (<connected-to-audio_ADCDAT>),               //                audio.ADCDAT
		.audio_ADCLRCK              (<connected-to-audio_ADCLRCK>),              //                     .ADCLRCK
		.audio_BCLK                 (<connected-to-audio_BCLK>),                 //                     .BCLK
		.audio_DACDAT               (<connected-to-audio_DACDAT>),               //                     .DACDAT
		.audio_DACLRCK              (<connected-to-audio_DACLRCK>),              //                     .DACLRCK
		.audio_clk_clk              (<connected-to-audio_clk_clk>),              //            audio_clk.clk
		.audio_pll_ref_clk_clk      (<connected-to-audio_pll_ref_clk_clk>),      //    audio_pll_ref_clk.clk
		.audio_pll_ref_reset_reset  (<connected-to-audio_pll_ref_reset_reset>),  //  audio_pll_ref_reset.reset
		.av_config_SDAT             (<connected-to-av_config_SDAT>),             //            av_config.SDAT
		.av_config_SCLK             (<connected-to-av_config_SCLK>),             //                     .SCLK
		.expansion_jp1_export       (<connected-to-expansion_jp1_export>),       //        expansion_jp1.export
		.expansion_jp2_export       (<connected-to-expansion_jp2_export>),       //        expansion_jp2.export
		.hex3_hex0_export           (<connected-to-hex3_hex0_export>),           //            hex3_hex0.export
		.hex5_hex4_export           (<connected-to-hex5_hex4_export>),           //            hex5_hex4.export
		.irda_TXD                   (<connected-to-irda_TXD>),                   //                 irda.TXD
		.irda_RXD                   (<connected-to-irda_RXD>),                   //                     .RXD
		.leds_export                (<connected-to-leds_export>),                //                 leds.export
		.ps2_port_CLK               (<connected-to-ps2_port_CLK>),               //             ps2_port.CLK
		.ps2_port_DAT               (<connected-to-ps2_port_DAT>),               //                     .DAT
		.ps2_port_dual_CLK          (<connected-to-ps2_port_dual_CLK>),          //        ps2_port_dual.CLK
		.ps2_port_dual_DAT          (<connected-to-ps2_port_dual_DAT>),          //                     .DAT
		.pushbuttons_export         (<connected-to-pushbuttons_export>),         //          pushbuttons.export
		.sdram_addr                 (<connected-to-sdram_addr>),                 //                sdram.addr
		.sdram_ba                   (<connected-to-sdram_ba>),                   //                     .ba
		.sdram_cas_n                (<connected-to-sdram_cas_n>),                //                     .cas_n
		.sdram_cke                  (<connected-to-sdram_cke>),                  //                     .cke
		.sdram_cs_n                 (<connected-to-sdram_cs_n>),                 //                     .cs_n
		.sdram_dq                   (<connected-to-sdram_dq>),                   //                     .dq
		.sdram_dqm                  (<connected-to-sdram_dqm>),                  //                     .dqm
		.sdram_ras_n                (<connected-to-sdram_ras_n>),                //                     .ras_n
		.sdram_we_n                 (<connected-to-sdram_we_n>),                 //                     .we_n
		.sdram_clk_clk              (<connected-to-sdram_clk_clk>),              //            sdram_clk.clk
		.slider_switches_export     (<connected-to-slider_switches_export>),     //      slider_switches.export
		.system_pll_ref_clk_clk     (<connected-to-system_pll_ref_clk_clk>),     //   system_pll_ref_clk.clk
		.system_pll_ref_reset_reset (<connected-to-system_pll_ref_reset_reset>), // system_pll_ref_reset.reset
		.vga_CLK                    (<connected-to-vga_CLK>),                    //                  vga.CLK
		.vga_HS                     (<connected-to-vga_HS>),                     //                     .HS
		.vga_VS                     (<connected-to-vga_VS>),                     //                     .VS
		.vga_BLANK                  (<connected-to-vga_BLANK>),                  //                     .BLANK
		.vga_SYNC                   (<connected-to-vga_SYNC>),                   //                     .SYNC
		.vga_R                      (<connected-to-vga_R>),                      //                     .R
		.vga_G                      (<connected-to-vga_G>),                      //                     .G
		.vga_B                      (<connected-to-vga_B>),                      //                     .B
		.vga_pll_ref_clk_clk        (<connected-to-vga_pll_ref_clk_clk>),        //      vga_pll_ref_clk.clk
		.vga_pll_ref_reset_reset    (<connected-to-vga_pll_ref_reset_reset>),    //    vga_pll_ref_reset.reset
		.video_in_TD_CLK27          (<connected-to-video_in_TD_CLK27>),          //             video_in.TD_CLK27
		.video_in_TD_DATA           (<connected-to-video_in_TD_DATA>),           //                     .TD_DATA
		.video_in_TD_HS             (<connected-to-video_in_TD_HS>),             //                     .TD_HS
		.video_in_TD_VS             (<connected-to-video_in_TD_VS>),             //                     .TD_VS
		.video_in_clk27_reset       (<connected-to-video_in_clk27_reset>),       //                     .clk27_reset
		.video_in_TD_RESET          (<connected-to-video_in_TD_RESET>),          //                     .TD_RESET
		.video_in_overflow_flag     (<connected-to-video_in_overflow_flag>)      //                     .overflow_flag
	);

