//Generated by DefParser v1.0 on Nov 16, 2009 12:07:51 PM.
//This file has been automatically generated.
//Edit contents with extreme caution.

`ifdef KEEP
 `undef KEEP
`endif
`ifdef PRESERVE
 `undef PRESERVE
`endif
`ifdef DEBUG
 `define KEEP (* keep *)
 `define PRESERVE (* preserve *)
`else
 `define KEEP
 `define PRESERVE
`endif

